### PR TITLE
Migrate Sentry to new SDK

### PR DESCRIPTION
**Pull request by wetneb**
For #2340.

This only updates to the new SDK, without solving the problem of logging personal information from users.
It looks like we are already trying to log some personal fields (user name, user email), so a first step would probably be to exclude those? I think @mbastian also had some heuristics to hide user names from paths in mind.

### CODE REVIEW

**Comment by wetneb** [comment]
Also, it seems that the format of the PUSH_URL has changed in this new API: it is now expecting something of the form `"https://examplePublicKey@o0.ingest.sentry.io/0"`, and we currently have something with `app.getsentry.com` instead of `ingest.sentry.io`. Not having access to the Sentry account I could not update this URL myself. I also wonder if this URL should be made public in the code (as it currently is) or if it should rather be injected at packaging time (as a secret).

**Comment by wetneb** [comment]
This does not work yet: somehow the `com.google.code.gson` library is not reachable at runtime:
```
[INFO] java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
[INFO] 	at io.sentry.EnvelopeReader.<init>(EnvelopeReader.java:22)
[INFO] 	at io.sentry.SentryOptions.<init>(SentryOptions.java:90)
[INFO] 	at io.sentry.SentryOptions.empty(SentryOptions.java:1560)
[INFO] 	at io.sentry.NoOpHub.<init>(NoOpHub.java:15)
[INFO] 	at io.sentry.NoOpHub.<clinit>(NoOpHub.java:13)
[INFO] 	at io.sentry.Sentry.<clinit>(Sentry.java:24)
[INFO] 	at org.gephi.branding.desktop.reporter.ReportController.<init>(ReportController.java:88)
```

**Comment by wetneb** [comment]
@mbastian this seems good to go for me know. I only tested this manually (triggering a fake exception) and it did get reported in Sentry.

I restored the user email field because it is actually provided on a voluntary basis by the user. If we do not want that, we should remove that field from the UI.

The paths that appear in the exception report do still contain the user name (at least for me), so that is not anonymised, but I do not see an obvious way to do that.

**Comment by mbastian** [comment]
> @mbastian this seems good to go for me know. I only tested this manually (triggering a fake exception) and it did get reported in Sentry.
> 

Awesome! I checked out the exception and everything seems to be nicely organised there.

> I restored the user email field because it is actually provided on a voluntary basis by the user. If we do not want that, we should remove that field from the UI.

OK, sounds good. Let's leave the UI field for now as it's additional work.

> 
> The paths that appear in the exception report do still contain the user name (at least for me), so that is not anonymised, but I do not see an obvious way to do that.

Thanks for taking a closer look. I had found this [capability](https://docs.sentry.io/platforms/java/data-management/sensitive-data/) but it doesn't seem it will do anything for us here. It means we should scrub this PII information ourselves from the logs. My recommendation is to try to cover the most common cases with a simple search/replace based on regex:
- /home/XXX
- \Users\XXX
- /Users/XXX

What do you think?

**Review by mbastian — APPROVED** [review]
Looks great

**Review by wetneb — COMMENTED** [review]
I added some regex to anonymize stuff, with some tests to demonstrate. No guarantee it is bullet proof of course…

**Review by mbastian — APPROVED** [review]
Nice work!

**Pull request merged**
