### PR TITLE
Fixed typo in german translation of statistics plugin

### PR DESCRIPTION
**Pull request by Gram21**

### CODE REVIEW

**Comment by eduramiba** [comment]
Hi,
We manage translations at https://www.transifex.com/gephi/gephi/dashboard
Can you add the changes there? If not, I can do it there for you later.

**Comment by Gram21** [comment]
Yeah, I have some troubles creating an account there and logging in, so it would be better if you could do that for me.

**Comment by eduramiba** [comment]
Oh okay, thanks!

**Comment by eduramiba** [comment]
Fixed in commit 4072c9e85d0affc19ee015e0c92257d3f8bf9650

**Pull request closed without merging**
