### PR TITLE
Fix for #2088

### PR DESCRIPTION
**Pull request by jbliesener**
This should fix issue #2088. Please check if the call to getVisibleOctantsIterator() in updateLOD() should be changed as well:

https://github.com/gephi/gephi/blob/56b8733f03a3aaaa4bcc3ca63744c803f9d7a4c3/modules/VisualizationImpl/src/main/java/org/gephi/visualization/opengl/CompatibilityEngine.java#L451

### CODE REVIEW

**Comment by eduramiba** [comment]
Hi,
Thanks for the pull request.

I will check and merge it as soon as possible. But this code will be replaced with the new [visualization engine](https://github.com/gephi/viz-engine) (work in progress).

**Comment by jbliesener** [comment]
Thank you, Eduardo. This issue has become critical and the change is relatively simple. I understand that it's not a priority for users that only select nodes visually, but as soon as you start using VisualizationController.selectNodes and some of these nodes are out of the currently visible network, you run into issues.

I'd appreciate if you could provide a quick fix through the regular 0.9.2 update channels. Thank you very much.

**Comment by jbliesener** [comment]
Oh, and please ignore the reverted "Install gephi.conf with user write privilege" fix. It has nothing to do with this issue. It was a try to give a non-admin user on Windows write privilege on the gephi.conf file, but I wasn't able to test it due to missing pre-requisites, so I abandoned it. However, I had already commited it to my private repo, so I decided to undo it.

Having said that, if you find some time, you may want to test it...

**Comment by jbliesener** [comment]
New VizEngine looks exciting!

**Comment by eduramiba** [comment]
Sorry for the delay, I need to find the time to merge and release updates for this.

**Pull request merged**
