### PR TITLE
Use dynamic URLs for JRE download.

### LINKED ISSUE #2424: Improve JRE download URLs to get the latest release for a given Java version
The packaging process currently relies on static URLs to download JREs for all three platforms.
This means that the bundled JREs might not be as fresh as they could be.
Using recent JREs has various benefits: more up to date root SSL certs, latest vulnerability fixes, and probably some bug fixes from time to time.

We could instead use dynamic URLs which redirect to the latest release of the JRE for a given Java version.
There is an API documented here: https://api.adoptium.net/q/swagger-ui/#/Binary/getBinary

For instance this will return the latest Java 11 JRE for Mac:
https://api.adoptium.net/v3/binary/latest/11/ga/mac/x64/jre/hotspot/normal/eclipse?project=jdk

That would be a good candidate to replace the static link we currently have:
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jre_x64_mac_hotspot_11.0.13_8.tar.gz

### PR DESCRIPTION
**Pull request by wetneb**
Closes #2424.

And now I am off to replicating Gephi's amazing setup to OpenRefine!

### CODE REVIEW

**Comment by eduramiba** [comment]
Thanks @wetneb Looks good to me!

**Review by eduramiba — APPROVED** [review]

**Comment by wetneb** [comment]
Note: I have a doubt about whether the setup (with or without this PR) works for Windows. Because for Windows, the JRE is downloaded as a `.zip` file, but is then extracted using `tar -zxf`, which should not work. It might be worth checking.

**Comment by wetneb** [comment]
Actually, no it should work when run on Windows, because somehow recent versions of Windows include `bsdtar` as `tar`. Mind blown!

**Comment by mbastian** [comment]
Amazing, I was wondering how to do that. Thanks!

**Pull request merged**
